services:
  - type: web
    name: Subscribe Notification
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: gunicorn app:app
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0