services:
  - type: web
    name: Subscribe Notification
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
        libnss3 \
        libatk-bridge2.0-0 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libgbm1 \
        libasound2 \
        libpangocairo-1.0-0 \
        libgtk-3-0 \
        libxss1 \
        libxtst6 \
        libenchant-2-2 \
        libsecret-1-0 \
        libmanette-0.2-0 \
        libgstreamer-gl1.0-0 \
        libgstreamer-plugins-base1.0-0 \
        libgles2
      pip install -r requirements.txt
      playwright install
    startCommand: gunicorn app:app
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /tmp/playwright